### ISSUE TITLE
when running 'python main.py', i encountered this

### ISSUE THREAD

**Issue by insorker** [insorker/yori#2]
Traceback (most recent call last):
  File "main.py", line 211, in <module>
    yori_render(cfg, Environment(loader=FileSystemLoader(cfg['templates'])))
  File "main.py", line 159, in yori_render
    page.page_render()
  File "main.py", line 74, in page_render
    self.page_render_markdown()
  File "main.py", line 86, in page_render_markdown
    for key, value in yaml_header.items():
AttributeError: 'str' object has no attribute 'items'

**Comment by insorker** [comment]
In your yaml header, you should add a ' ' between "xxx:" and your content, e.g.
```title:<space>hello world```
